# Python on Linux Web App

name: Deploy gaPython app on Azure VM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using secretkey
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo killall python3
            rm -rf gaPython
            git clone https://github.com/anurago9o9/gaPython
            cd gaPython
            git checkout master
            sudo pip install flask
            sudo python3 App.py
